# shopify.app.toml

name = "eurozone-dual-currency-display"
client_id = "94be870f0498bac664dfccb02475dfa4"
application_url = "https://shopify-currency-converter-production.up.railway.app"
embedded = true

[auth]
redirect_urls = [
  "https://shopify-currency-converter-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://asapxt-teststore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Увери се, че read_orders е тук, за да може бекендът да чете поръчките
scopes = "read_orders,write_themes"

# В тази секция е важната промяна
[[build.extensions]]
type = "ui_extension"
name = "EuroZone Currency Display"
handle = "eurozone-currency-display"

[build.extensions.targeting]
# Тук са дефинирани страниците, на които ще се показва разширението
targets = [
  "purchase.checkout.block.render",
  "purchase.thank-you.block.render",
  "customer-account.order-status.block.render" # Добавяме и таргет за клиентския акаунт
]

# Тази секция дава право на разширението да прави мрежови заявки
[build.extensions.capabilities]
network_access = true