Replace your shopify.extension.toml with the following. This will correctly bind api_access (and your other settings) to the one UI extension that renders on the Order Status page:

# extensions/order-status-currency-display/shopify.extension.toml
api_version = "2024-10"    # bump to the latest supported version

# Declare a list of extensions (we have exactly one)
[[extensions]]
  type   = "ui_extension"
  name   = "Order Status Currency Display"
  handle = "order-status-currency-display"

  # Grant this extension access to the Order API
  [extensions.capabilities]
    api_access     = true
    block_progress = false

  # Where and how to run your React block
  [[extensions.targeting]]
    target            = "customer-account.order-status.block.render"
    module            = "./src/OrderStatus.jsx"
    default_placement = "ORDER_SUMMARY1"

  # Optional: wire up your settings panel
  [extensions.settings]
    [[extensions.settings.fields]]
      key         = "show_rate_info"
      type        = "boolean"
      name        = "Show exchange rate info"
      description = "Display the current EUR/BGN exchange rate"
      default     = true

    [[extensions.settings.fields]]
      key         = "highlight_euro_switch"
      type        = "boolean"
      name        = "Highlight Euro switch date"
      description = "Show prominent notice about automatic EUR switch on 01.01.2026"
      default     = true